BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Tag_assign" (
	"FK_text"	INTEGER NOT NULL,
	"FK_tag"	INTEGER NOT NULL,
	FOREIGN KEY("FK_tag") REFERENCES "Tags"("ID_tag"),
	FOREIGN KEY("FK_text") REFERENCES "Texts"("ID_text")
);
CREATE TABLE IF NOT EXISTS "Tags" (
	"ID_tag"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Tag"	TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "Texts" (
	"ID_text"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Text"	TEXT NOT NULL UNIQUE,
	"FK_author"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "authors" (
	"ID_author"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"author"	TEXT NOT NULL UNIQUE
);
COMMIT;
